### PR TITLE
Adding rest of the components

### PR DESCRIPTION
**Pull request by aniket91**
Incremental PR for EXTANG-4
Following components are implemented as part of this PR-
1. All components under charts
2. All components under PivotGrid
3. All components under D3
4. Panels, Popups, Tabbar Tabs, Lists, Wizard - Under components
Known issues-
1. D3
    1.1 Hierarchy
          1.1.1 Org chart(No such component)
          1.1.2 sunburst/Tree(Tree class not loading)
          1.1.3 Zoomable sunburst Component (zooming is not working)
2. Components
  2.1  Panels - Resizeable Panel Component (unable to resize from the corner)
  2.2. Tabs - All tabs are not rendered currently gives an error.
  2.3. Touch Events (rendering issues)
  2.4 Wizrd (rendering issues)

### CODE REVIEW

**Comment by branflake2267** [comment]
@jnsencha

**Comment by jnsencha** [comment]
@aniket91 please provide relevant JIRA in PRs and / or in commit messages for ease of tracking, thanks. For now I am linking https://sencha.jira.com/browse/EXTANG-4

**Comment by jnsencha** [comment]
After running npm install at the root, then attempting to run kitchensink with npm start I get nothing showing in the browser a 7+ console errors. @aniket91 Is this to be expected?

**Comment by jnsencha** [comment]
Component -> Drag and Drop -> Files does not work

**Comment by jnsencha** [comment]
@aniket91 Step 2 of 3 on the Wizard component does not show. 1 and 3 do

**Comment by jnsencha** [comment]
@aniket91 I need the following:

- [ ] Resolve issues in EditableTree.js that prevent loading of Kitchensink (console errors, etc.)
- [ ] Provide a list of what work, which components, is /are ready for testing / verification
- [ ] Include The JIRA item in commit messages, in this case it's EXTANG-4, for integrated tracking
- [ ] Keep up the good work!

**Comment by jnsencha** [comment]
@aniket91 @alishaAgr  Please review the below:

- Charts
    - Refresh data button for all charts, currently only a few have it
- Pivot Grids
    - Compact Layout
        - lags when alternating Expand All and Collapse All
    - Collapsable
        - no collapsing happening, not able to collapse rows or columns based on selection
    - Range Editor
        - Collapse / Expand performance issues (lag)
    - Missing Pivot Grids
        - Row Styling
        - Cell Styling
        - Remote Calculations
- D3 Issues:
    - Tree
        - does not load
    - Configurable TreeMap
        - does not load
    - Missing D3
        - Custom SVG group of components
        - Custom Canvas group of components
        - Hierarchy -> Words component
- Components
    - Panels
        - Advanced Date Panel
            - Console error: core.js:14597 ERROR TypeError: Cannot read property 'focus' of undefined
        - Time Panel
            - Missing Clock icon
            - Container not sized properly
        - Missing Panels
            - Resizable Split
            - Header position
            - Complex Collapsible
    - Popups
        - Dialog
            - Can only show dialog 1 time, does not show multiple times
            - Full screen does not work, small popover still visible over full screen dialog
        - Missing Popups
            - Overlays
                - Missing Picker, Toast, and Action Sheet
            - Toast
                - Missing multi-line toast and long text toast
    - Tabs
        - TabBar
            - Active tag text not updating
    - Lists
        - Grouped
            - Index bar scroll down to z then back to a list is not rendered until you scroll down
        - Pull Refresh
            - No pull to refresh icon and no data refresh when attempting pull to refresh
        - Paging
            - Uncaught TypeError: Cannot read property 'isWidget' of null
        - Undoable Step Swiper
            - Delete not showing as an option, shows as edit then shifts to delete undo. Doesn’t match example
    - Wizard
        - 2nd step in wizard does not display, though the code exists for it to be there

**Pull request merged**
